Vagrant.configure("2") do |config|

    config.env.enable
    config.vm.box = ENV['vm_box']

    config.vm.define 'elevatevm'
    # amount of time for upgrade on reboot to complete
    config.vm.boot_timeout = ENV['vm_boot_timeout'].to_i

    config.vm.provider "libvirt" do |v|
        v.memory = 12288
        v.cpus = 4

        # Redirect output from the serial console of the VM to the file
        v.serial :type => "file", :source => {:path => ENV['vm_serial_log']}
    end

    config.vm.provision "shell", inline: <<-SHELL
        if [ "$(rpm --eval %rhel)" = "7" ]; then
            if grep -i centos /etc/redhat-release >/dev/null; then
                sudo curl -o /etc/yum.repos.d/CentOS-Base.repo https://el7.repo.almalinux.org/centos/CentOS-Base.repo
            fi
            if grep -i scientific /etc/redhat-release >/dev/null; then
                sed -i 's/\$slreleasever/7/g' /etc/yum.repos.d/*.repo
            fi
        fi
        sudo yum -y -q install dnf
        sudo dnf -y -q update
    SHELL

    # Reboot after upgrade
    config.vm.provision :reload

end